# This is a basic workflow to help you get started with Actions

#name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
      push:
            branches: 
                  - '*'
                  - '!master' 
      
name: Main Workflow

jobs:
      coverage_test:
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v2
                  - name: Set up Python
                    uses: actions/setup-python@v2
                    with:
                          python-version: '3.x' 
                  - name: Install dependencies and run coverage
                    run: |
                          python -m pip install --upgrade pip
                          pip install coverage
                          coverage run -m unittest -v && coverage report -m
                  - name: Generate xml coverage report
                    run: |
                          coverage xml -i}
                  - name: ls 
                    run: |
                          ls -lh
      sonarcloud:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
            with:
              # Disabling shallow clone is recommended for improving relevancy of reporting
              fetch-depth: 0
          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
